name: football_picks
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.14.0
  fluttertoast: ^8.0.9

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.13
  flutter_keyboard_visibility: ^5.2.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

